server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non_contextual_creation: true
    properties:
      hibernate:
        show_sql: true
#  output:
#    ansi:
#      enabled: always

logging:
  level:
    com.ead: trace
    root: info
    org.springframework.web: debug
    org.hibernate: debug

ead:
  api:
    url:
      authuser: 'http://localhost:8087'